### PR TITLE
Modify j2 template to use namespacing 1-level deep

### PR DESCRIPTION
**Pull request by lenards**
The `BUILD_ENV` file (aka `variables.yml\@{{build_env_name}}`) was defined
in a manner that flattened the overall namespace and caused errors when
substituting.

What this meant was, variables like `SERVER_URL` that appear in multiple
sections (but with different forms, like 1. no protocol 2. with slash,
etc) were being collapsed into the _last occurrence_ parsed in the YAML
definition. This has unintended consequences. This changed uses the
intended "namespace of multiple _sections_" form.

Ultimately, this template will be removed and the `BUILD_ENV` will become
a _single source of truth_ (which will be used to generate any other
configuration files needed in the installation, configuration &
deployment of Atmosphere).

## Re-stating the problem definition with examples

If you consider the following YAML definition used to provide configuration: 
```
dev:/var/lib/jenkins/jobs/Build_Test_Atmosphere/workspace/atmosphere# grep SERVER_URL ../atmo-extras/clank_init/build_env/variables.yml@atmo-dev+jenkins 
        SERVER_URL: https://atmo-dev.iplantc.org
        DJANGO_SERVER_URL: https://atmo-dev.iplantc.org
        SERVER_URL: https://atmo-dev.iplantc.org
        DJANGO_SERVER_URL: https://atmo-dev.iplantc.org
        SERVER_URL: https://atmo-dev.iplantc.org
        SERVER_URL: atmo-dev.iplantc.org
```

There all appear at the *_same_* level within [`TROPO`](https://github.com/iPlantCollaborativeOpenSource/clank/blob/master/dist_files/variables.yml.dist#L212-L237) or [`ATMO`](https://github.com/iPlantCollaborativeOpenSource/clank/blob/master/dist_files/variables.yml.dist#L78-L110)

This means that the last definition, `SERVER_URL: atmo-dev.iplantc.org`, will be used in *all* templates - regardless of their "context".

This means that the `[COMMON]` has a `SERVER_URL = atmo-dev.iplantc.org`, not `https://atmo-dev.iplantc.org:

```ini
[COMMON]
....
DJANGO_SERVER_URL = https://atmo-dev.iplantc.org 
SERVER_URL = atmo-dev.iplantc.org 
....
```

## Confirmation 

For Atmosphere, there is *no* variation in `SERVER_URL` definitions - they *all* include the protocol:
```
/var/lib/jenkins/jobs/Build_Test_Atmosphere/workspace/atmosphere# grep SERVER_URL variables.ini
SERVER_URL = https://atmo-dev.iplantc.org
DJANGO_SERVER_URL = https://atmo-dev.iplantc.org
SERVER_URL = https://atmo-dev.iplantc.org
```

For Troposphere, there is a _"no protocol"_ `SERVER_URL` definition:
```
dev:/var/lib/jenkins/jobs/Build_Test_Troposphere/workspace/troposphere# grep SERVER_URL variables.ini
DJANGO_SERVER_URL = https://atmo-dev.iplantc.org
SERVER_URL = https://atmo-dev.iplantc.org
SERVER_URL = atmo-dev.iplantc.org
```

### CODE REVIEW

**Comment by lenards** [comment]
- [ ] secrets repo has a `add-expected-namespace-handling` for just the dev (with & without Jenkins)
- [ ] alter all build_env files to have correct _nesting_

**Comment by lenards** [comment]
I'm validating the edits I'm making to the build_env files with this: https://gist.github.com/lenards/8bc83707ae48cdee4df4

**Comment by steve-gregory** [comment]
Your gist would make a great `./manage.py <command>` in either atmosphere or troposphere.. I dont know if its "out of scope" or not though..

**Comment by steve-gregory** [comment]
LG2M! This is a great first-pass at the fix. Ready to merge when you have completed the checklisted items mentioned above. :shipit:

**Comment by lenards** [comment]
Just to show that this does fix are most *notably* issue... 

_Note: the names of _innocent_ servers have been adjusted to protect their street cred..._

the handling with `SERVER_URL` in `troposphere/settings/local.py` needs to have the _protocol scheme_ included in the template-merge occurrences: 

```diff
dev:/opt/dev/troposphere# diff troposphere/settings/local.py troposphere/settings/local.py.bak.20160212_150054 
9c9
< SERVER_URL="https://super-dev.iplantc.org"
---
> SERVER_URL="super-dev.iplantc.org"
21,23d20
< SUPPORT_EMAIL="support@iplantcollaborative.org"
< 
< 
27,28d23
< ORG_NAME= "iPlant Collaborative"
< 
115c110
< # WEB_SH_URL = "https://super-dev.iplantc.org/https://super-dev.iplantc.org/web_shell"
---
> # WEB_SH_URL = "super-dev.iplantc.org/https://super-dev.iplantc.org/web_shell"
```

So: 
- the _left_ side (`<`) is the corrected, expected merge (after this PR is in place)
- the _right_ side (`>`) is the "world is a flat _namespace_" approach 

But, we have *not* _undone_ the "no protocol scheme" occurrences _either_:

```diff
dev:/opt/dev/troposphere/extras/nginx# diff site.conf site.conf.bak.20160212_150114 
dev:/opt/dev/troposphere/extras/nginx# grep super-dev site.conf
    return 301 https://super-dev.iplantc.org$request_uri;
    server_name super-dev.iplantc.org;
dev:/opt/dev/troposphere/extras/nginx# grep atmo-dev site.conf.bak.20160212_150114 
    return 301 https://super-dev.iplantc.org$request_uri;
    server_name super-dev.iplantc.org;
dev:/opt/dev/troposphere/extras/nginx#

**Comment by lenards** [comment]
Moving to altering all `build-env` files.

**Comment by lenards** [comment]
Done altered `build_env` files. 

Provided a syntax check script in the secrets repo (it's called [`scripts/check_yaml.py`](https://gist.github.com/lenards/8bc83707ae48cdee4df4))

**Comment by lenards** [comment]
Okay. Merged `build_env` changes

Moving forward :shipit: 

- [ ] verify builds all green for jenkins after change :white_check_mark:

**Comment by lenards** [comment]
[:white_check_mark:](https://imgflip.com/i/zdcl1)

**Pull request merged**
