### PR TITLE
Provided a build-type flag to signal dev or prod versions.

### PR DESCRIPTION
**Pull request by lenards**
The type of build (_development or production_) is an important part of the configuration and deployment of troposphere. Right now, the build (performed by _webpack_ via _npm_ lifecycle script) defaults to a large/verbose development style that includes source-maps and full-text (about _~5.0 MB_). 

This pull request alters the `npm run build` task done via `shell` module to default to a _production_ build. This would be the default option for someone deploying Atmosphere (but not developing it). If a development version is desired, then a value of `development` for the variable  `TROPOSPHERE_BUILD` would be passed into the `build_troposphere.yml`,  `deploy_troposphere.yml`, or `deploy_stack.yml` playbook. 

We can provide value different than the **default**, ``production``, using `--extra-vars`:
```
  --extra-vars "TROPOSPHERE_BUILD=development"
```

Example:
```bash
export WORKSPACE="/opt/dev/coolit"
export ENV_FILE="variables.yml@staging"
...
python ratchet.py
...
ansible-playbook "$WORKSPACE/clank/playbooks/deploy_stack.yml" \
  --flush-cache  -c local -e @"$WORKSPACE/clank/$ENV_FILE" \
  -i "$WORKSPACE/clank/local_inventory" \
  --extra-vars "TROPOSPHERE_BUILD=development" \
  --skip "atmosphere" \
  -vvvv
``` 

Implementation Note: I have pulled the `--` flag into the declaration of the `shell` call to avoid having to escape the `--` when dealing with it on the command-line.

### CODE REVIEW

**Comment by lenards** [comment]
Hey, I am still working a bit on this. I just wanted to get the PR in place so I can refer to it via link (if needed). 

I still need to: 
- [ ] provide example
- [ ] provide information about var `TROPOSPHERE_BUILD`
- [ ] verify if `TROPOSPHERE_BUILD` can be overrode from `variables.yml`
- [ ] test on atmo-dev

**Comment by lenards** [comment]
If you were to run something like: 
```bash
$WORKSPACE/clank/clank_env/bin/ansible-playbook "$WORKSPACE/clank/playbooks/deploy_stack.yml" \
  --flush-cache \
  -c local \
  -e @"$WORKSPACE/clanker/$ENV_FILE" \
  -i "$WORKSPACE/clanker/local_inventory" \
  --extra-vars "TROPOSPHERE_BUILD=development" \
  --skip "atmosphere" \
  -vvvv
```

You can see that `development` will be used in the `npm run build` command as an environment variable. 

```
TASK: [troposphere-setup-troposphere | run npm build] ************************* 
<localhost> REMOTE_MODULE command chdir=/opt/dev/troposphere npm run build --development #USE_SHELL
<localhost> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1452556232.27-70021169603802 && echo $HOME/.ansible/tmp/ansible-tmp-1452556232.27-70021169603802']
... 
changed: [localhost] => {"changed": true, "cmd": "npm run build --development", "delta": "0:00:36.391172", ... 
```

Now - let's pass in `--extra-vars "TROPOSPHERE_BUILD=production"` 

```bash
$WORKSPACE/clanker/clank_env/bin/ansible-playbook "$WORKSPACE/clanker/playbooks/deploy_stack.yml" \
  --flush-cache \
  -c local \
  -e @"$WORKSPACE/clanker/$ENV_FILE" \
  -i "$WORKSPACE/clanker/local_inventory" \
  --extra-vars "TROPOSPHERE_BUILD=production" \
  --skip "atmosphere" \
  -vvvv
```

The output shows the flag being passed through:
```
TASK: [troposphere-setup-troposphere | run npm build] ************************* 
<localhost> REMOTE_MODULE command chdir=/opt/dev/troposphere npm run build --production #USE_SHELL
<localhost> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1452556525.88-203440844574126 && echo $HOME/.ansible/tmp/ansible-tmp-1452556525.88-203440844574126']
<localhost> PUT /tmp/tmp8Kd6VB TO /root/.ansible/tmp/ansible-tmp-1452556525.88-203440844574126/command
<localhost> EXEC ['/bin/sh', '-c', u'LANG=C LC_CTYPE=C /usr/bin/python /root/.ansible/tmp/ansible-tmp-1452556525.88-203440844574126/command; rm -rf /root/.ansible/tmp/ansible-tmp-1452556525.88-203440844574126/ >/dev/null 2>&1']
... 
changed: [localhost] => {"changed": true, "cmd": "npm run build --production", "delta": "0:01:56.309468",
```

Also, `TROPOSPHERE_BUILD` will **default** to `production` if no variable is present in the `$ENV_FILE` or passed via `--extra-vars`.


```bash
$WORKSPACE/clanker/clank_env/bin/ansible-playbook "$WORKSPACE/clanker/playbooks/deploy_stack.yml" \
   --flush-cache  \
   -c local  \
   -e @"$WORKSPACE/clanker/$ENV_FILE"   \
   -i "$WORKSPACE/clanker/local_inventory"  \
  --skip "atmosphere"   -vvvv
```

Output:
```
TASK: [troposphere-setup-troposphere | run npm build] ************************* 
<localhost> REMOTE_MODULE command chdir=/opt/dev/troposphere npm run build --production #USE_SHELL
<localhost> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1452556899.68-9936354555082 && echo $HOME/.ansible/tmp/ansible-tmp-1452556899.68-9936354555082']
<localhost> PUT /tmp/tmpm7akef TO /root/.ansible/tmp/ansible-tmp-1452556899.68-9936354555082/command
<localhost> EXEC ['/bin/sh', '-c', u'LANG=C LC_CTYPE=C /usr/bin/python /root/.ansible/tmp/ansible-tmp-1452556899.68-9936354555082/command; rm -rf /root/.ansible/tmp/ansible-tmp-1452556899.68-9936354555082/ >/dev/null 2>&1']
changed: [localhost] => {"changed": true, "cmd": "npm run build --production", "delta": "0:01:51.761788", 
```

**Comment by lenards** [comment]
Override in `variables.yml`
-----------------------------------

So `$ENV_FILE` is really equal to: `"variables.yml@atmo-dev"`.

I've defined a variable there, `TROPOSPHERE_BUILD`, that was not present before: 
```
# grep _BUILD variables.yml@atmo-dev
TROPOSPHERE_BUILD: "debug"
```

With this value, "debug", we want to see that this is passed along to `npm run build` without passing anything via `--extra-vars`:
```
$WORKSPACE/clanker/clank_env/bin/ansible-playbook "$WORKSPACE/clanker/playbooks/deploy_stack.yml" \
   --flush-cache  \
   -c local  \
   -e @"$WORKSPACE/clanker/$ENV_FILE"   \
   -i "$WORKSPACE/clanker/local_inventory"  \
  --skip "atmosphere"   -vvvv
```

Success :white_check_mark: 
```
TASK: [troposphere-setup-troposphere | run npm build] ************************* 
<localhost> REMOTE_MODULE command chdir=/opt/dev/troposphere npm run build --debug #USE_SHELL
<localhost> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1452557329.25-247268545142910 && echo $HOME/.ansible/tmp/ansible-tmp-1452557329.25-247268545142910']
<localhost> PUT /tmp/tmpCfgLFw TO /root/.ansible/tmp/ansible-tmp-1452557329.25-247268545142910/command
<localhost> EXEC ['/bin/sh', '-c', u'LANG=C LC_CTYPE=C /usr/bin/python /root/.ansible/tmp/ansible-tmp-1452557329.25-247268545142910/command; rm -rf /root/.ansible/tmp/ansible-tmp-1452557329.25-247268545142910/ >/dev/null 2>&1']
changed: [localhost] => {"changed": true, "cmd": "npm run build --debug", "delta": "0:00:36.672513",
...
```

**Comment by lenards** [comment]
@amercer1 / @steve-gregory - ready for review :heavy_check_mark:

**Comment by steve-gregory** [comment]
Excellent! I think we will probably see more uses for the use of "prod" vs "debug" setups in other areas of the application.. A few that come to mind:
* "Production" vs "Developer" celery default
* `settings.DEBUG`

LG2M :+1:

**Comment by lenards** [comment]
I do think that I should probably commit `TROPOSPHERE_BUILD: "development"` for `variables.yml@atmo(dev|beta)` before merging this.

**Comment by lenards** [comment]
- [ ] This also needs to be merged into `stable` before it will get picked up on the build servers.

**Comment by lenards** [comment]
Variable is defined in the appropriate `build_env` files. 

```yml
...
TROPOSPHERE_BUILD: "development"
...
```

**Pull request merged**
