### PR TITLE
Fixed issue with SSL generation on each execution

### PR DESCRIPTION
**Pull request by lenards**
This moves the `CREATE_SSL_FILES` variable from `roles/setup-ssl/vars` to `roles/setup-ssl/defaults` to avoid "clobbering" the variable passed to the role via the `deploy_atmosphere.yml` playbook. 

Because we shifted to passing in parameters to roles (and variable precedence changed), the `CREATE_SSL_FILES: False` passed via `--extra_vars @$ENV_FILE` was being "clobbered" (or, overidden, if you like) by the variable in [roles/setup-ssl/vars/main.yml](https://github.com/iPlantCollaborativeOpenSource/clank/blob/v2.0/roles/setup-ssl/vars/main.yml#L1). 

Files for testing and verifying the changes are made available via a git-cloneable gist:
```
git clone https://gist.github.com/lenards/501e788da736ed42d10cdc42c8f4353e clank-pr
```

### CODE REVIEW

**Comment by lenards** [comment]
I got a 👍  from @steve-gregory in chat.

**Comment by lenards** [comment]
:shipit:

**Comment by lenards** [comment]
Will wait for any more feedback ....

**Comment by cdosborn** [comment]
👍  We could really move to having more error checking like you demonstrate. 

I had to wrestle to get the vm to run.

**Comment by cdosborn** [comment]
Being able to test a demo is highly appreciated tho.

**Comment by lenards** [comment]
The vm piece was not really well laid out. 

The `check_parameter.yml` is something that Strootman showed me as a pattern that Core Software is used.

**Pull request merged**
