### PR TITLE
app-backup-files now de-references symlinks in source; removed some copy-paste cruft from app-backup-files role; updated instructions pointing to new role template

### PR DESCRIPTION
**Pull request by c-mart**

### CODE REVIEW

**Comment by c-mart** [comment]
@amercer1, it looks like you made a conflicting change after I originally submitted this PR. Your roles/app-backup-files/tasks/main.yml specifies `cp -rRL` which is redundant (`-r` and `-R` do the same thing). My PR specifies `cp -Lr` which is no more than needed to do the job.

**Comment by amercer1** [comment]
Hey @c-mart. Good call on the `cp -rRL` being redundant. That was something I was going to get to after the our next deployment, but you beat me to it! I would fix whatever the merge conflict is, and I would be happy to merge PR.

**Comment by c-mart** [comment]
@amercer1 the merge conflict is the `cp` line as I commented on yesterday. I don't know of a way to resolve the conflict without merging my own PR. If you're merging then I believe you must resolve the conflict.

**Comment by c-mart** [comment]
Never mind, I figured it out - merged in changes from upstream and resolved the conflict. This PR is certified conflict-free. @amercer1, merge away.

**Comment by amercer1** [comment]
💃

**Pull request merged**
