### PR TITLE
Add callback plugin for human readable error output

### PR DESCRIPTION
**Pull request by amercer1**
After an embarrassing meeting and having trouble reading output from the configure script, I have added a callback plugin that will make spit the output as intended.

Takes this:

```
 TASK [app-generate-ini-config : run generate script for app] *******************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "/opt/env/troposphere/bin/python /opt/dev/troposphere/configure", "delta": "0:00:00.166891", "end": "2016-06-27 11:59:02.153102", "failed": true, "rc": 1, "start": "2016-06-27 11:59:01.986211", "stderr": "", "stdout": "\u001b[30m\u001b[46m\nProject Path => /opt/dev/troposphere\u001b[0m\n\n\nTesting for preconditions...\n\n\u001b[31mError found in /opt/dev/troposphere/troposphere/settings/local.py.j2\u001b[0m\n\u001b[33mUndeclared variables found in /opt/dev/troposphere/troposphere/settings/local.py.j2: \n\t- AUTH_ENABLE_LDAP\n\t- AUTH_ENABLE_CAS\n\t- AUTH_ENABLE_MOCK\n\t- AUTH_ENABLE_OAUTH\n\t- AUTH_ENABLE_MODEL\n\t- AUTH_USE_OVERRIDE\n\t- AUTH_ENABLE_GLOBUS \n\u001b[0m\n\u001b[33mUnused variables found in section local.py: \n\t- OAUTH_ISSUE_USER\n\u001b[0m\n\u001b[33mUnused variables found in section COMMON: \n\t- DJANGO_SERVER_URL\n\t- LDAP_SERVER\n\t- LDAP_SERVER_DN\n\u001b[0m\n\n\n\u001b[31mConfiguration files were not generated.\n\u001b[0m\n\u001b[30m\u001b[41mFAILED.\u001b[0m ", "stdout_lines": ["\u001b[30m\u001b[46m", "Project Path => /opt/dev/troposphere\u001b[0m", "", "", "Testing for preconditions...", "", "\u001b[31mError found in /opt/dev/troposphere/troposphere/settings/local.py.j2\u001b[0m", "\u001b[33mUndeclared variables found in /opt/dev/troposphere/troposphere/settings/local.py.j2: ", "\t- AUTH_ENABLE_LDAP", "\t- AUTH_ENABLE_CAS", "\t- AUTH_ENABLE_MOCK", "\t- AUTH_ENABLE_OAUTH", "\t- AUTH_ENABLE_MODEL", "\t- AUTH_USE_OVERRIDE", "\t- AUTH_ENABLE_GLOBUS ", "\u001b[0m", "\u001b[33mUnused variables found in section local.py: ", "\t- OAUTH_ISSUE_USER", "\u001b[0m", "\u001b[33mUnused variables found in section COMMON: ", "\t- DJANGO_SERVER_URL", "\t- LDAP_SERVER", "\t- LDAP_SERVER_DN", "\u001b[0m", "", "", "\u001b[31mConfiguration files were not generated.", "\u001b[0m", "\u001b[30m\u001b[41mFAILED.\u001b[0m "], "warnings": []}
```

and converts it to:
```
33mUndeclared variables found in /opt/dev/troposphere/troposphere/settings/local.py.j2: \n\t- AUTH_ENABLE_LDAP\n\t- AUTH_ENABLE_CAS\n\t- AUTH_ENABLE_MOCK\n\t- AUTH_ENABLE_OAUTH\n\t- AUTH_ENABLE_MODEL\n\t- AUTH_USE_OVERRIDE\n\t- AUTH_ENABLE_GLOBUS \n\u001b[0m\n\u001b[33mUnused variables found in section local.py: \n\t- OAUTH_ISSUE_USER\n\u001b[0m\n\u001b[33mUnused variables found in section COMMON: \n\t- DJANGO_SERVER_URL\n\t- LDAP_SERVER\n\t- LDAP_SERVER_DN\n\u001b[0m\n\n\n\u001b[31mConfiguration files were not generated.\n\u001b[0m\n\u001b[30m\u001b[41mFAILED.\u001b[0m ", "stdout_lines": ["\u001b[30m\u001b[46m", "Project Path => /opt/dev/troposphere\u001b[0m", "", "", "Testing for preconditions...", "", "\u001b[31mError found in /opt/dev/troposphere/troposphere/settings/local.py.j2\u001b[0m", "\u001b[33mUndeclared variables found in /opt/dev/troposphere/troposphere/settings/local.py.j2: ", "\t- AUTH_ENABLE_LDAP", "\t- AUTH_ENABLE_CAS", "\t- AUTH_ENABLE_MOCK", "\t- AUTH_ENABLE_OAUTH", "\t- AUTH_ENABLE_MODEL", "\t- AUTH_USE_OVERRIDE", "\t- AUTH_ENABLE_GLOBUS ", "\u001b[0m", "\u001b[33mUnused variables found in section local.py: ", "\t- OAUTH_ISSUE_USER", "\u001b[0m", "\u001b[33mUnused variables found in section COMMON: ", "\t- DJANGO_SERVER_URL", "\t- LDAP_SERVER", "\t- LDAP_SERVER_DN", "\u001b[0m", "", "", "\u001b[31mConfiguration files were not generated.", "\u001b[0m", "\u001b[30m\u001b[41mFAILED.\u001b[0m "], "warnings": []}

cmd: /opt/env/troposphere/bin/python /opt/dev/troposphere/configure

start: 2016-06-27 12:06:58.546635

end: 2016-06-27 12:06:58.695857

delta: 0:00:00.149222

stdout: 
Project Path => /opt/dev/troposphere


Testing for preconditions...

Error found in /opt/dev/troposphere/troposphere/settings/local.py.j2
Undeclared variables found in /opt/dev/troposphere/troposphere/settings/local.py.j2: 
        - AUTH_ENABLE_LDAP
        - AUTH_ENABLE_CAS
        - AUTH_ENABLE_MOCK
        - AUTH_ENABLE_OAUTH
        - AUTH_ENABLE_MODEL
        - AUTH_USE_OVERRIDE
        - AUTH_ENABLE_GLOBUS 

Unused variables found in section local.py: 
        - OAUTH_ISSUE_USER

Unused variables found in section COMMON: 
        - DJANGO_SERVER_URL
        - LDAP_SERVER
        - LDAP_SERVER_DN



Configuration files were not generated.

FAILED. 
```
The plugin also revels what shell and command module commands are being ran as a bonus.

### CODE REVIEW

**Comment by steve-gregory** [comment]
:shipit: :ship:

**Comment by lenards** [comment]
This is one of my favorite pull requests! 🌠

**Comment by lenards** [comment]
Thank you for researching this Andre! 👍 

🚢 :shipit: ⛵

**Comment by amercer1** [comment]
haha. Thanks everybody!

💃

**Pull request merged**
