### PR TITLE
v2.0

### PR DESCRIPTION
**Pull request by lenards**
- [`CHANGELOG.md`](https://github.com/iPlantCollaborativeOpenSource/clank/blob/v2.0/CHANGELOG.md) outlines all work/features in v2.0.0 milestone
   * b392465 & 2820352
- [`RELEASE_NOTES.md`](https://github.com/iPlantCollaborativeOpenSource/clank/blob/v2.0/RELEASE_NOTES.md) provided
   * 322604e

### CODE REVIEW

**Comment by lenards** [comment]
@amercer1 - when we are ready to merge this, we can *Close* the [v2.0 Milestone](https://github.com/iPlantCollaborativeOpenSource/clank/milestones).

**Comment by amercer1** [comment]
💯 💃

**Comment by lenards** [comment]
We need to delete the v2.0.0 tag and re-point it at what will be the final v2.0 release.

**Comment by lenards** [comment]
The release tag has been deleted. 

For reference, this is how I delete it:
```
$ git push origin :refs/tags/v2.0.0
```

**Comment by lenards** [comment]
After #113 - I think I want to investigate the following situations that might be _similar_ or related in variable precedence issues: 

```
$ find . -name 'main.yml' | grep 'vars'
./roles/app-alter-kernel-for-imaging/vars/main.yml
./roles/app-config-logging/vars/main.yml
./roles/noc-enable-new-relic/vars/main.yml
./roles/setup-elasticsearch/vars/main.yml
./roles/setup-kibana/vars/main.yml
./roles/setup-logstash/vars/main.yml
./roles/setup-postgres/vars/main.yml
./roles/setup-virtualenv/vars/main.yml
```

I believe that the following are not called and not maintained:
- ./roles/setup-elasticsearch/vars/main.yml
- ./roles/setup-kibana/vars/main.yml
- ./roles/setup-logstash/vars/main.yml

So I will investigate the following cases:
- [ ] ./roles/app-alter-kernel-for-imaging/vars/main.yml
- [ ] ./roles/app-config-logging/vars/main.yml
- [ ] ./roles/noc-enable-new-relic/vars/main.yml
- [ ] ./roles/setup-postgres/vars/main.yml
- [ ] ./roles/setup-virtualenv/vars/main.yml

**Comment by amercer1** [comment]
You are correct in that the ELK roles are no longer being used. We are using Strootman's roles to do the deployments. Example can be seen [here](https://github.com/cyverse/ansible-elasticsearch). So I will create a PR to remove those.

**Comment by amercer1** [comment]
PR can be found [here](https://github.com/iPlantCollaborativeOpenSource/clank/pull/114).

**Comment by lenards** [comment]
I have completed the review the remaining 5 roles with `vars/main.yml` files. I'll put it together as a PR for review and considerations\*\*.

\*\* I am curious if we should not remove the `main.yml` file under `.../vars` altogether. For the 5 roles, 3 of them had empty files.

**Comment by steve-gregory** [comment]
Double-checking: @amercer1 @lenards is this PR ready to go?

**Comment by lenards** [comment]
I think this is ready. 
🚢

**Comment by lenards** [comment]
We should keep `v2.0` branch for now because continuous integration scripts and local enviroments (vagrant) still operate off of this branch.

**Pull request merged**
